# StrikeKitsRegen Configuration
# Plugin by mDevelopment for Minemalia Network
# 
# This plugin automatically regenerates player stats after kills in StrikePractice FFA arenas
# You can configure what gets regenerated and create exceptions for specific arenas or kits

# =============================================================================
# HEALTH REGENERATION
# =============================================================================
health:
  # Should players be healed to full health after killing someone in FFA?
  enabled: true
  
  # Arenas where health regeneration is DISABLED
  # Use the exact arena names from StrikePractice
  excluded_arenas:
    - "Soup FFA"
    - "UHC FFA"
  
  # Kits where health regeneration is DISABLED
  # Use the exact kit names from StrikePractice
  excluded_kits:
    - "Soup"
    - "UHC"

# =============================================================================
# HUNGER REGENERATION  
# =============================================================================
hunger:
  # Should players have their hunger restored after killing someone in FFA?
  enabled: true
  
  # Arenas where hunger regeneration is DISABLED
  excluded_arenas:
    - "NoHunger FFA"
  
  # Kits where hunger regeneration is DISABLED
  excluded_kits:
    - "Creative"

# =============================================================================
# KIT RESTORATION
# =============================================================================
kit:
  # Should players have their kit items restored after killing someone in FFA?
  # This restores the player's custom kit layout, or the default kit if no custom layout exists
  enabled: true
  
  # Arenas where kit restoration is DISABLED
  excluded_arenas:
    - "BuildUHC FFA"
  
  # Kits where kit restoration is DISABLED
  excluded_kits:
    - "BuildUHC"
    - "Archer"

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
general:
  # Enable debug messages in console (useful for troubleshooting)
  debug: false
  
  # Delay in ticks before applying regeneration effects (20 ticks = 1 second)
  # Set to 0 for instant regeneration
  delay_ticks: 0