name: StrikeKitsRegen
version: '${version}'
main: net.minemalia.strikekitsregen.StrikeKitsRegen
api-version: '1.21'
folia-supported: true
depend: [StrikePractice]
authors: [mDevelopment]
description: Regenerates player health, hunger, and kits after kills in StrikePractice FFA arenas
website: https://github.com/minemalia/StrikeKitsRegen

commands:
  strikekitsregen:
    description: Main plugin command
    aliases: [skr]
    permission: strikekitsregen.admin
    usage: /<command> [reload]

permissions:
  strikekitsregen.admin:
    description: Access to plugin administration commands
    default: op